language: node_js
node_js:
  - "7"
sudo: required
services:
  - docker
install:
  - npm install -g now
script:
  - docker run -v "$PWD:/srv/jekyll" jekyll/jekyll:pages jekyll build
deploy:
  provider: script
  skip_cleanup: true
  script: cd _site && now -t $NOW_TOKEN
  on:
    branch: master